# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.6'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'client' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => true,
    :fabric_enabled => true
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # General dSYM settings for all pods
        config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
        config.build_settings['GCC_GENERATE_DEBUGGING_SYMBOLS'] = 'YES'
        config.build_settings['DEBUGGING_SYMBOLS'] = 'YES'
        
        # Critical: Don't strip symbols during copy
        if config.name == 'Release'
          config.build_settings['COPY_PHASE_STRIP'] = 'NO'
          config.build_settings['STRIP_INSTALLED_PRODUCT'] = 'NO'
        end
      end
      
      # Specific fixes for Hermes
      if target.name == 'hermes-engine'
        target.build_configurations.each do |config|
          # These are the critical settings for Hermes dSYM generation
          config.build_settings['SKIP_INSTALL'] = 'NO'
          config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
          config.build_settings['DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT'] = 'YES'
          config.build_settings['DWARF_DSYM_FILE_NAME'] = 'hermes.framework.dSYM'
          config.build_settings['GENERATE_INFOPLIST_FILE'] = 'YES'
          config.build_settings['DEFINES_MODULE'] = 'YES'
          
          # Ensure dSYM generation even for Release
          config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
          config.build_settings['GCC_GENERATE_DEBUGGING_SYMBOLS'] = 'YES'
          
          # Don't strip the binary
          config.build_settings['STRIP_STYLE'] = 'non-global'
          config.build_settings['DEAD_CODE_STRIPPING'] = 'NO'
          config.build_settings['STRIP_INSTALLED_PRODUCT'] = 'NO'
          config.build_settings['COPY_PHASE_STRIP'] = 'NO'
        end
      end
    end
    
    # Additional fix for iOS 15+ and Xcode 14+
    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.6'
        end
      end
    end
  end
end